### ISSUE TITLE
Fix Medusa decryption

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gov-ui#32]
It used to work fine, but we get this error: 

```
Error: Authenticated decryption failed
    at HGamalSuite.decryptFromMedusa (webpack-internal:///./node_modules/@medusa-network/medusa-sdk/lib/src/encrypt.js:124:42)
    at async Medusa.decrypt (webpack-internal:///./node_modules/@medusa-network/medusa-sdk/lib/src/index.js:165:31)
    at async decrypt (webpack-internal:///./src/pages/proposal/[proposalId]/index.tsx:113:40)
```

http://localhost:3000/proposal/102478032364470671344165103499702370832657112225882291472103392593084102105200/

**Comment by julienbrg** [comment]
Won't fix as it's not in the priorities for now.
